pub const Op = enum(u8) {
    push_bool_true,
    push_bool_false,
    push_i32_literal,
    push_i32_stack,
    add_i32,
    sub_i32,
    mul_i32,
    div_i32,
    mod_i32,
    pow_i32,
    println,
    print_bool,
    print_i32,
};
