name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.13.0 # released versions or master

      - name: Install Rebo
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/graeme-lockley/rebo-lang/main/tasks/install.sh)" -- ./rebo
          echo "$(pwd)/rebo/bin" >> $GITHUB_PATH
    
      - name: Install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
  
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Install Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.10"

      - name: Verify Gradle
        working-directory: ./components/compiler-kotlin
        run: gradle --version
        
      - name: Generate Instructions Opcodes
        run: |
          ./tasks/generate_ops

      - name: Build Bendu Compiler
        working-directory: ./components/compiler-kotlin
        run: |
          ./tasks/generate_parser
          ./gradlew test
          ./gradlew build
          ./tasks/build_fat_jar

      - name: Build Bendu Bytecode Interpreter
        working-directory: ./components/bci-zig
        run: |
          zig build test
          zig build

      - name: Acceptance Tests
        run: |
          ./bin/
