name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.13.0 # released versions or master

      - name: Install Rebo
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/graeme-lockley/rebo-lang/main/tasks/install.sh)" -- ./rebo
          echo "$(pwd)/rebo/bin" >> $GITHUB_PATH
    
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '23'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate Instructions Opcodes
        run: |
          ./tasks/generate_ops

      - name: Build Bendu Compiler
        run: |
          cd ./components/compiler-kotlin
          ./tasks/build_fat_jar
          ./gradlew build
          ./gradlew test
          ./tasks/build_fat_jar

      - name: Build Bendu Bytecode Interpreter
        run: |
          cd ./components/bci-zig
          zig build test
          zig build

      - name: Acceptance Tests
        run: |
          ./bin/
